export { default as SideMenu } from "./SideMenu";
export { menuStructure } from "./menu";
export { DEFAULT_DISCOVERY_MENU_GROUP, DEFAULT_DISCOVERY_MENU_URL } from "./config";
export { fetchDiscoveryMenu, fetchDiscoveryMenuItems, mapDiscoveryMenuToMenuItems, mapDiscoveryMenuResponse } from "./discoveryClient";
export type { DiscoveryMenuResult } from "./discoveryClient";
export type { AppBaseUrls, AppId, DiscoveryMenuConfig, MenuItem } from "./types";
export { TRF_UI_VERSION } from "./version";
export { logout } from "./logout";
export { TranslationClient } from "./translationClient";

// UI components
export { Button } from "./components/Button";
export type { ButtonProps, ButtonVariant, ButtonSize } from "./components/Button";
export { LinkButton } from "./components/LinkButton";
export type { LinkButtonProps } from "./components/LinkButton";
export { Input } from "./components/Input";
export type { InputProps, InputSize } from "./components/Input";
export { Select } from "./components/Select";
export type { SelectProps } from "./components/Select";
export { Textarea } from "./components/Textarea";
export { Field } from "./components/Field";
export type { FieldProps } from "./components/Field";
export { PageHeader } from "./components/PageHeader";
export type { PageHeaderProps } from "./components/PageHeader";
export { TableCard } from "./components/TableCard";
export type { TableCardProps } from "./components/TableCard";
export { Badge } from "./components/Badge";
export type { BadgeProps, BadgeColor } from "./components/Badge";
export { EmptyState } from "./components/EmptyState";
export type { EmptyStateProps } from "./components/EmptyState";
export { Spinner } from "./components/Spinner";
export type { SpinnerProps, SpinnerSize } from "./components/Spinner";
